// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateTrackPoints implements pgx.CopyFromSource.
type iteratorForCreateTrackPoints struct {
	rows                 []CreateTrackPointsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTrackPoints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTrackPoints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].SequenceNumber,
		r.rows[0].RecordedAt,
		r.rows[0].Latitude,
		r.rows[0].Longitude,
		r.rows[0].ElevationMeters,
		r.rows[0].SpeedMps,
		r.rows[0].HeartRate,
		r.rows[0].Cadence,
	}, nil
}

func (r iteratorForCreateTrackPoints) Err() error {
	return nil
}

func (q *Queries) CreateTrackPoints(ctx context.Context, arg []CreateTrackPointsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"track_points"}, []string{"run_id", "sequence_number", "recorded_at", "latitude", "longitude", "elevation_meters", "speed_mps", "heart_rate", "cadence"}, &iteratorForCreateTrackPoints{rows: arg})
}
