// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Run struct {
	ID                 pgtype.UUID
	SourceFileID       pgtype.UUID
	StartedAt          pgtype.Timestamptz
	DistanceMeters     float64
	ElapsedTimeMs      int64
	TimerTimeMs        int64
	Calories           pgtype.Int4
	TotalAscentMeters  pgtype.Float8
	TotalDescentMeters pgtype.Float8
	CreatedAt          pgtype.Timestamptz
}

type SourceFile struct {
	ID            pgtype.UUID
	Filename      string
	Checksum      string
	StoragePath   string
	FileSizeBytes int64
	ImportedAt    pgtype.Timestamptz
}

type Split struct {
	ID             pgtype.UUID
	RunID          pgtype.UUID
	LapNumber      int32
	DistanceMeters float64
	ElapsedTimeMs  int64
	TimerTimeMs    int64
}

type TrackPoint struct {
	ID              pgtype.UUID
	RunID           pgtype.UUID
	SequenceNumber  int32
	RecordedAt      pgtype.Timestamptz
	Latitude        float64
	Longitude       float64
	ElevationMeters pgtype.Float8
	SpeedMps        pgtype.Float8
	HeartRate       pgtype.Int2
	Cadence         pgtype.Int2
}
