// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :one

INSERT INTO runs (
  source_file_id,
  started_at,
  distance_meters,
  elapsed_time_ms,
  timer_time_ms,
  calories,
  total_ascent_meters,
  total_descent_meters
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id
`

type CreateRunParams struct {
	SourceFileID       pgtype.UUID
	StartedAt          pgtype.Timestamptz
	DistanceMeters     float64
	ElapsedTimeMs      int64
	TimerTimeMs        int64
	Calories           pgtype.Int4
	TotalAscentMeters  pgtype.Float8
	TotalDescentMeters pgtype.Float8
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.SourceFileID,
		arg.StartedAt,
		arg.DistanceMeters,
		arg.ElapsedTimeMs,
		arg.TimerTimeMs,
		arg.Calories,
		arg.TotalAscentMeters,
		arg.TotalDescentMeters,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
