// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceFile = `-- name: CreateSourceFile :one
INSERT INTO source_files (
  filename,
  checksum, 
  storage_path, 
  file_size_bytes
)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSourceFileParams struct {
	Filename      string
	Checksum      string
	StoragePath   string
	FileSizeBytes int64
}

func (q *Queries) CreateSourceFile(ctx context.Context, arg CreateSourceFileParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSourceFile,
		arg.Filename,
		arg.Checksum,
		arg.StoragePath,
		arg.FileSizeBytes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
