// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: splits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSplit = `-- name: CreateSplit :one
INSERT INTO splits (
    run_id,
    lap_number,
    distance_meters,
    elapsed_time_ms,
    timer_time_ms
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateSplitParams struct {
	RunID          pgtype.UUID
	LapNumber      int32
	DistanceMeters float64
	ElapsedTimeMs  int64
	TimerTimeMs    int64
}

func (q *Queries) CreateSplit(ctx context.Context, arg CreateSplitParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSplit,
		arg.RunID,
		arg.LapNumber,
		arg.DistanceMeters,
		arg.ElapsedTimeMs,
		arg.TimerTimeMs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
