// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track_points.sql

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTrackPointsParams struct {
	RunID           pgtype.UUID
	SequenceNumber  int32
	RecordedAt      pgtype.Timestamptz
	Latitude        float64
	Longitude       float64
	ElevationMeters pgtype.Float8
	SpeedMps        pgtype.Float8
	HeartRate       pgtype.Int2
	Cadence         pgtype.Int2
}
